name: flutter_projects
description: "A Flutter project with theme and language switching."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0  # For state management (theme and language switching)
  shared_preferences: ^2.0.15  # For saving theme and language preferences
  flutter_localizations:
    sdk: flutter  # For localization support
  intl: ^0.19.0  # Internationalization (i18n) package for language translations
  flutter_bloc: ^8.0.0  # If you need bloc for state management (optional)
  http: ^1.2.2  # For making HTTP requests (optional, if needed)
  share_plus: ^4.0.8  # For sharing content (optional)
  animated_splash_screen: ^1.3.0  # For adding an animated splash screen (optional)
  lottie: ^3.1.0  # For Lottie animations (optional)
  cupertino_icons: ^1.0.6  # Cupertino icons for iOS styling

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Recommended lints for Flutter

flutter:
  uses-material-design: true
  generate: true  # Enable code generation for localization files

  assets:
    - assets/images/  # Directory for image assets

